from tkinter import *
window = Tk()
window.title('Tkinter Sample Window')
window.geometry('400x400')
greeting = Label(text="Hello User", fg='black', bg='white')
button = Button(text="click me", fg='black', bg='white')
entry = Entry(fg="yellow", bg="blue", width=50)
greeting.pack()
button.pack()
entry.pack()
frame = Frame(master=window, relief=RAISED, borderwidth=5)
frame.pack()
label = Label(master=frame, text="sample frame")
label.pack()
textbox = Text(fg='green', bg='yellow')
textbox.pack()
window.mainloop()